version: '2'
services:
  gpmaster:
     image: 10.0.0.96:5000/database/gp_final:v3 
     hostname: master
     container_name: gp_master
     labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: key1=102
     networks: 
       - docker_gwbridge
     ports:
       - "20032:2345"
       - "28080:28080"
     volumes:
       - /opt/gpmaster/gpdata_final:/home/gpadmin/gpdata
       - /opt/gpmaster/conf_final:/home/gpadmin/conf
     privileged: true
     tty: true
     mem_limit: 20g
  gpnode1:
     image: 10.0.0.96:5000/database/gp_final:v2
     hostname: sdw1
     labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: key1=104
     networks: 
       - docker_gwbridge
     ports:
       - "20041:40000"
       - "20042:40001"
     volumes:
       - /opt/gpnode1/gpdata_final:/home/gpadmin/gpdata
     privileged: true
     tty: true
     mem_limit: 20g
  gpnode2:
     image: 10.0.0.96:5000/database/gp_final:v2
     hostname: sdw2
     labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: key1=100
     networks: 
       - docker_gwbridge
     ports:
       - "20045:40000"
       - "20046:40001"
     volumes:
       - /opt/gpnode2/gpdata_final:/home/gpadmin/gpdata
     privileged: true
     tty: true
     mem_limit: 20g
